Repository vkoves/electrify-chicago, pull requests merged in 2025-08, with the labels that each got.

#196 Create A Streamlined Print Mode for Flyers with QR Code
  package.json
  src/components/BuildingImage.vue
  src/components/BuildingsTable.vue
  src/components/EmailBuildingModal.vue
  src/components/OwnerLogo.vue
  src/components/ReportCard.vue
  src/components/ReportingTile.vue
  src/components/StatTile.vue
  src/components/graphs/PieChart.vue
  src/scss/global.scss
  src/templates/BuildingDetails.vue
  static/icons/printer.svg
  yarn.lock
Labels: enhancement, frontend

#192 Add Initial Citywide Stats Page
  package.json
  run_all.py
  src/common-functions.vue
  src/components/graphs/ScatterGraph.vue
  src/constants/citywide-stats-graph-data.vue
  src/data/dist/historic-stats.json
  src/data/scripts/generate_historic_stats.py
  src/pages/About.vue
  src/pages/Citywide-Stats.vue
  src/scss/colors.scss
  tests/data/scripts/unit/test_generate_historic_stats.py
  tsconfig.json
Labels: enhancement, frontend

#217 Add basic 404 page
  .stylelintrc.json
  src/pages/404.vue
  src/pages/Index.vue
  src/scss/global.scss
Labels: enhancement, frontend

#223 Improved All Electric & New Building Labelling
  eslint.config.mjs
  src/common-functions.vue
  src/components/BuildingTile.vue
  src/components/BuildingsTable.vue
  src/components/OverallRankEmoji.vue
  src/components/ReportCard.vue
  src/components/StatTile.vue
  src/components/layout/AppHeader.vue
  src/pages/BiggestBuildings.vue
  src/pages/CleanestBuildings.vue
  src/pages/HighestEmissionsIntensity.vue
  src/pages/Index.vue
  src/pages/LatestUpdates.vue
  src/pages/RetrofitChicagoParticipants.vue
  src/pages/Search.vue
  src/pages/TopElectricityUsers.vue
  src/pages/TopEmitters.vue
  src/pages/TopGasUsers.vue
  src/pages/blog/GHGIntensityPredictCompliance.vue
  src/scss/colors.scss
  src/scss/global.scss
  src/templates/BuildingDetails.vue
  src/templates/BuildingOwner.vue
  src/templates/Ward.vue
Labels: bug, enhancement, frontend

#226 Rename Gas Free Buildings to All Electric Buildings
  src/components/StatTile.vue
  src/pages/About.vue
  src/pages/AllElectric.vue
  src/pages/BiggestGasFreeBuildings.vue
  src/pages/blog/HowWeGradeBuildings.vue
  src/templates/BuildingDetails.vue
Labels: enhancement
